
          #+++++++++++++++++++++++|       <>       |++++++++++++++++++++++#
          #     file for generating the container postgres database       #
          #     and pg admin



version: "3.9"

services:
  # PostgreSQL Service
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POST_USER_NAME}
      POSTGRES_PASSWORD: ${POST_PASSWORD}
      POSTGRES_DB: ${POST_DATABASE}
      POSTGRES_PORT: 5432
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - postgresVolume:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./user.sql:/docker-entrypoint-initdb.d/user.sql
  # pgAdmin Service
  pgadmin:
    container_name: pgadmin
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - 8080:8080
    volumes:
      - pgadminVolume:/var/lib/pgadmin
#    depends_on:
#      - postgres

# Named Volumes
volumes:
  postgresVolume:
  pgadminVolume: